#! /bin/sh

#### AUTOSTART ####
sxhkd &
picom &
~/.fehbg &
~/.config/polybar/launch.sh &
nm-applet &
pa-applet &
pkill pa-applet
mpd &
dunst &
#xautolock -time 15 -locker 'betterlockscreen -l' &
killall bspswallow
pidof ~/.local/bin/bspswallow || ~/.local/bin/bspswallow &

#### MONITORS ####
bspc monitor eDP-1 -d 一 二 三 四 	五 	六 七 八 九
bspc monitor HDMI-1 -d 一 二 三 四 	五 	六 七 八 九

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config border_radius                 50
bspc config window_gap                    20
bspc config top_padding                   0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM RULES ####
bspc rule -a "SFML Game!" state=floating

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a main)
xdo below -t $(xdo id -n root) $(xdo id -a main)


